// packages/ui-components/vue/src/FeedbackForm.vue
<template>
  <form>
    <label>
      Name
      <input id="name" type="text" name="name" required />
    </label>
    <label>
      Email
      <input id="email" type="email" name="email" required />
    </label>
    <label>
      Message
      <textarea id="message" name="message" required />
    </label>
    <button>Send</button>
  </form>
</template>

// packages/ui-components/preact/src/FeedbackForm.tsx
export default function Form() {
  return (
    <form>
      <label>
        Name
        <input type="text" id="name" name="name" required />
      </label>
      <label>
        Email
        <input type="email" id="email" name="email" required />
      </label>
      <label>
        Message
        <textarea id="message" name="message" required />
      </label>
      <button>Send</button>
    </form>
  );
}
